//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWestLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compound
    {
        public int LTNumber { get; set; }
        public int SequenceCode { get; set; }
        public string CompoundName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateArrived { get; set; }
        public string ReceivedBy { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string Appearance { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> MolecularMass { get; set; }
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        public Nullable<decimal> MaxTotalDose { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
