//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWestLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionalApproval
    {
        public int ConditionalApprovalID { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<int> AssayID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public string ApproverName { get; set; }
        public string Comments { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ProtocolNotebook ProtocolNotebook { get; set; }
        public virtual Test Test { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
