//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWestLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeBankInfo
    {
        public int EmployeeID { get; set; }
        public string BankAccount { get; set; }
        public string RoutingNumber { get; set; }
        public string AccountType { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
