//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWestLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvioceItem
    {
        public int InvoiceItemID { get; set; }
        public int InvoiceID { get; set; }
        public int AssayID { get; set; }
        public int WorkOrderID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Modified { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual ProtocolNotebook ProtocolNotebook { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
