//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWestLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResult()
        {
            this.TestResultComments = new HashSet<TestResultComment>();
        }
    
        public int TestResultsID { get; set; }
        public int TestID { get; set; }
        public int AssayOrderID { get; set; }
        public int TestTubeID { get; set; }
        public int LTNumber { get; set; }
        public Nullable<System.DateTime> ScheduleStart { get; set; }
        public byte[] TextFile { get; set; }
        public byte[] NumericFile { get; set; }
        public int StatusID { get; set; }
        public System.DateTime StatusUpdatedDate { get; set; }
        public bool RunAgain { get; set; }
        public int RunNumber { get; set; }
        public string ModifedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual AssayOrder AssayOrder { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResultComment> TestResultComments { get; set; }
        public virtual Test Test { get; set; }
        public virtual TestTube TestTube { get; set; }
    }
}
