//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWestLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestCondition
    {
        public int TestConditionsID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> ConditionalOnID { get; set; }
        public string Condition { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Test Test1 { get; set; }
    }
}
